### ISSUE TITLE
Customisation issues

### ISSUE THREAD

**Issue by kmaustral** [manic/obsidian-wrap-with-shortcuts#1]
This is a great start. But I have trouble because it is not clear what the syntax for the shortcuts is. Could it be handled just in the hotkeys section of Obsidian? Also, it would be good to be able to edit the wraps, rather than delete and start over again.

**Comment by manic** [comment]
@kmaustral Thanks for your feedback! The updated version was released([1.1.0](https://github.com/manic/obsidian-wrap-with-shortcuts/releases/tag/1.1.0)) and please take a look :)
