### ISSUE TITLE
if one tag is empty don't cancel operation

### ISSUE THREAD

**Issue by 1C0D** [manic/obsidian-wrap-with-shortcuts#10]
I did a little plugin to insert ↓↑ with a shortcut. but I realized I could do it, with your plugin. except if I fill only one tag, I have to put a space in the other one. It's not too much, but I guess without this condition, it wouldn't change too much the behavior. if tag empty, insert "". It could allow inserting special characters, or even successions of emoticons, like stars in front matter, for instance.

**Comment by manic** [comment]
@1C0D Could you give me some examples? like what is the command and what is the wrapper tag

**Comment by 1C0D** [comment]
@manic  Name: arrow-down StartTag:(empty)  EndTag:↓ So if no selection it will insert ↓ and if selection ↓ at the end 
I've already thought about having only the first tag, but I don't remember why now.
Another interesting thing would be a way to insert a return \n.
