### ISSUE TITLE
Feature Request: allow for creating start and end tags in new, separate lines

### ISSUE THREAD

**Issue by YousufSSyed** [manic/obsidian-wrap-with-shortcuts#17]
This would be useful for quickly creating code blocks. So If I select text like this:
`Text`
and made a shortcut to add ``` on separate lines like this (without the slashes, formatting is tricky!):

```
\```
Text
\```
```

There could be a checkbox in the shortcut editor to choose to make tags in separate lines.

**Comment by manic** [comment]
@YousufSSyed I think you can do this in the latest version now.
Close this issue. :)
