### ISSUE TITLE
[Feature Request] Order the Wrappers

### ISSUE THREAD

**Issue by AtlcatlQ** [manic/obsidian-wrap-with-shortcuts#6]
I would like to order the wrappers to get the things more organized as I Use a lot of wrappers. So a thing like a UP/down button or something to drag them would be useful.

**Comment by manic** [comment]
Because obsidian would automatically sort the Wrap shortcuts with alphabet order (case insensitive), so I think it would be better to do the same way 

<img width="295" alt="image" src="https://user-images.githubusercontent.com/74136/188320735-4f0f0e63-38f1-4df7-8a70-4f1c9401c022.png">

**Comment by AtlcatlQ** [comment]
I think that I'm OK with that solution.
